# -*- coding: utf-8 -*-
"""advisor_tasks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhJDjxAgZyJxQzZcmVOaeKQ5PjIc2Y3K
"""

##*****************************************************************************************************************************************************
##There are three tasks: 1) energy_level_assessment_task , 2) musical_genre_and_culture_identification_task , and 3) dancing_preference_assessment_task
##*****************************************************************************************************************************************************

from crewai import Task
from textwrap import dedent
from datetime import date

class Advisor_Tasks():

    def energy_level_assessment_task(self, agent, origin, destination, answers):
        return Task(
            description=dedent(f"""
                You will be presented with an individual, or group of individuals, seeking guidance with assessing their current energy-levels to assist with decisions of what Paris bars and nightlife they should enjoy tonight.
                Use your knowledge of body language, energy-level sensitivity, emotional intelligence, and spreading energy to help develop strategies which the individual, or group of individuals, can utilize towards improvement and enjoyability of experiencing Paris nightlife.
                Use the {answers} to offer the best quality advice you have

                Origin: {origin}
                Destination: {destination}
                Answers: {answers}
                """),
            expected_output=dedent("""
                A cumulative summary of the conversation highlighting:
                1. Observations of energy levels exhibited by body language and energy sensitivities.
                2. Analysis of existing emotions using emotional intelligence to decipher which moods are currently possessed inside of the traveling tourists
                3. Recommended which bars and night clubs will be best suited to match the moods currently present in the traveling tourists.
                4. Also recommend any mental nightclub and bar hotlines in the {destination} if you have the correct information. Do not provide any inaccurate, unverified, or suspicious contact information.
                """),
            agent=agent,

        )

    def musical_genre_and_culture_identification_task(self, agent, origin, destination, interests):
        return Task(
          description=dedent(f"""
              Educate the user about musical genres and cultures existing in {destination}.
              Provide history of the origin of each musical genre and culture observed by the user to be existing in {destination}.
              Assess the users musical genre and culture preferences by establishing through questions what type of music the user is most comfortable with while visiting the city bars and nightclubs

              Origin: {origin}
              Destination: {destination}
              Interests: {interests}

              """),
          expected_output=dedent("""
              A musical genre and culture guide which includes:
              1. Most common and popular musical genres and cultural music.
              2. Local customs to be respected during immersion of one musical culture into another musical culture.
              3. Tips for discovering the musical genre or culture which best matches the users comfort preferences.
              4. Recommendations of bars and nightclubs possessing entertaining and relatable musical cultures and genres which can assist the user with more easily connecting to the local musical culture and genre.
              """),
          agent=agent
    )

    def dancing_preference_assessment_task(self, agent, origin, destination, interests):
      return Task(
          description=dedent(f"""
              You will be presented with an individual, or a group of individuals, seeking assistance with identifying which dancing styles they specifically prefer.
              Provide a history of the different dancing styles which have existed in {destination}, and discover which dancing styles the traveling tourists enjoy most through asking
              questions about which rhythms, beats, tempos, and grooves match with what they enjoy most.  Provide suggestions on which bars and night clubs the user can visit to re-experience and enjoy the
              preferred dancing styles.

              Origin: {origin}
              Destination: {destination}
              Interests: {interests}

              """),
          expected_output=dedent("""
              A dancing style preference guide which includes:
              1. dancing styles and their correlation with individual rhythym & tempo preferences.
              2. Local dancing style etiquette, customs, and traditions which may relate or differ with other countries.
              3. Suggestions for connecting with bars, nightclubs, and other nightlife people through sharing of dancing style preferences.
              4. Recommendations for bars and night clubs where the user can experience the dancing style which best matches their preferences
              """),
          agent=agent
    )

