# -*- coding: utf-8 -*-
"""advisor_agents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJWjsXhHk4Hi7BhlDRCQnTQH70LaReHp
"""

##***************************************************************************************************
## using the model "llama3-70b-8192" from chatGroq API.
## There are three agents: 1) energy_level , 2) musical_genre_and_culture , and 3) dancing_preference
##***************************************************************************************************

from crewai import Agent
from langchain_groq import ChatGroq
import os
from langchain_community.llms import HuggingFaceEndpoint


# using the model from Groq Cloud API
# need the API key
llm = ChatGroq(temperature=0.1, groq_api_key=GROQ_API_KEY, model_name="llama3-70b-8192")


class Night_Life_Advisor():

  def energy_level(self):
    return Agent(
        role='Energy Level Advisor',
        goal='Provide an assessment of the persons energy levels to assist with deciding night-life bar and club recommendations',
        backstory="""A specialist who has knowledge of body language, energy-level sensitivity, emotional intelligence, and how to spread energy when needed""",
        verbose=True,
        llm=llm,
        allow_delegation=False
    )

  def musical_genre_and_culture(self):
    return Agent(
        role='Musical Culture and Genre Advisor',
        goal='Educate the user about cultural music and musical genres existing in Paris, and help them connect with the music which lifts their spirits',
        backstory="""An expert in all types of music genres, and the cultural background history each type of music genre possesses. A guide devoted to assisting travelers with connecting to music. A guide who helps travelers understand more deeply the background cultural history of each bar and night-club which can provide the traveler more easily connect his or her individual cultural background with the bar or nightclubs history and background.""",
        verbose=True,
        llm=llm,
        allow_delegation=False
    )

  def dancing_style_preference(self):
    return Agent(
        role='Dancing Preference Advisor',
        goal='Gathers information from tourists about what styles of music and dancing they enjoy to help assist the travelers with finding a bar or night club which they can share their dancing skills at, or a bar or night club which does not have dancing',
        backstory="""A professional in multi-cultural dancing who is familiar with every dancing studio, dancing style, bar dancing, and nightclub dancing in existence in Paris. A guide which can provide recommendations on which bars or night clubs to visit according to the travelers dance style preferences""",
        verbose=True,
        llm=llm,
        allow_delegation=False
    )